name: teskura
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animations: ^1.1.2
  google_fonts: ^0.3.10
  provider: ^4.0.5
  firebase_auth: ^0.18.0
  firebase_core: ^0.5.0
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.14.0+2
  flutter_signin_button: ^1.0.0
  flutter_svg: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - images/

